# This file was generated by GoReleaser. DO NOT EDIT.
cask "sdd" do
  version "0.9.0"

  on_macos do
    on_intel do
      sha256 "8b7d7458ced161cb4f7f471e2a7c1cd6b3b25ba505d317145043b6499eecb81a"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "38b496f7bc2aa06c74346a3e8aac22baa7656ddf91693dbec4983cf3c5913a8f"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "fd35304f2f08d60582b143974afaa21c15957a1d00dea5c9cff1e6d6d8164e16"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5db98d101c32688458b51d8782af46cfda387792641b06347b50716c907712ee"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sdd"
  desc "Signal-Dialogue-Decision graph tool"
  homepage "https://github.com/networkteam/sdd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sdd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sdd"]
    end
  end

  # No zap stanza required

end
