# This file was generated by GoReleaser. DO NOT EDIT.
cask "sdd" do
  version "0.16.2"

  on_macos do
    on_intel do
      sha256 "68dd54a9c3dad01c72598c53dd7c3ad3f9e9965e5ad2630fc2c66a063c37d38c"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "68bb95cb6f56403521751dc8835d155a17582825ee39edacf37520af097a29b0"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "683da6dead5ec863b0a1ff59b1db088393fcb33a4153d15c066d9f5aed8065a0"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "5c34284fe9a9f7381bc70760452ac143766f176b92ac9b5fdbd0d8c5c55a5679"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sdd"
  desc "Signal-Dialogue-Decision graph tool"
  homepage "https://github.com/networkteam/sdd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sdd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sdd"]
    end
  end

  # No zap stanza required

end
