# This file was generated by GoReleaser. DO NOT EDIT.
cask "sdd" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "fa798d18fdbe5ecca5e913035babdba77a9348cf766e46344d9ab55eea166f49"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "2a8bb8d7b61d8910ce3686778b9adfbcb375d73cd69951a689a951d4b97fcdc8"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "e4abb8e2de3dba9c871f96f9824de21847d508fbd65044c1a8cf92d311d238ab"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "19a9b197cbb856197a40dfdf63327538da854322bff86efa1b689e7710942479"
      url "https://github.com/networkteam/sdd/releases/download/v#{version}/sdd_#{version}_linux_arm64.tar.gz"
    end
  end

  name "sdd"
  desc "Signal-Dialogue-Decision graph tool"
  homepage "https://github.com/networkteam/sdd"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "sdd"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/sdd"]
    end
  end

  # No zap stanza required

end
