# This file was generated by GoReleaser. DO NOT EDIT.
cask "shry" do
  desc "Shry - A tool description here"
  homepage "https://github.com/networkteam/shry"
  version "0.1.1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "shry"

  on_macos do
    on_intel do
      url "https://github.com/networkteam/shry/releases/download/v0.1.1/shry_Darwin_x86_64.tar.gz"
      sha256 "4dc31357a9ba717578b204a646d70ac581e1359977303e564a550285b8c0b9de"
    end
    on_arm do
      url "https://github.com/networkteam/shry/releases/download/v0.1.1/shry_Darwin_arm64.tar.gz"
      sha256 "08e7c2bf055abdc55820465584cc780313185a3a81b6f51a643fe1aaf88d083d"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/networkteam/shry/releases/download/v0.1.1/shry_Linux_x86_64.tar.gz"
      sha256 "8ce2dea874d20abcf55f9029f1949cc7f3685d1e56d5de094c9d1d4a88864f0a"
    end
    on_arm do
      url "https://github.com/networkteam/shry/releases/download/v0.1.1/shry_Linux_arm64.tar.gz"
      sha256 "74e322d08cdf87748d3ec0cec05da77a9140f6d74c9017a617a5ff37f3e47e3e"
    end
  end

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/shry"]
    end
  end

  # No zap stanza required
end
